device: cuda:0
attack_label_trans: all2one
attack_target: 0
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data/cifar10
frequency_save: 100
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: preactresnet18
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: SSBA_replace
epochs: 100
attack_train_replace_imgs_path: ../resource/ssba/cifar10_ssba_train_b1.npy
attack_test_replace_imgs_path: ../resource/ssba/cifar10_ssba_test_b1.npy