device: cuda:0
attack_label_trans: all2one
attack_target: 0
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data/cifar10
frequency_save: 100
img_size: [32, 32, 3]
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: preactresnet18
num_classes: 10
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: fix_patch
attack_trigger_loc:
  - - 26
    - 26
  - - 26
    - 27
  - - 27
    - 26
  - - 27
    - 27
trigger_ptn:
  - 0
  - 0
  - 0
  - 0
epochs: 100