attack_label_trans: all2one
attack_target: 0
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data/cifar10
frequency_save: 100
img_size: [32, 32, 3]
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: resnet18
num_classes: 10
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: blended
epochs: 100
attack_trigger_img_path: ../data/hello_kitty.jpeg
# just as in bdzoo1
attack_train_blended_alpha: 0.2
attack_test_blended_alpha: 0.2