device: cuda:0
attack_label_trans: all2one
attack_target: 0
batch_size: 32
client_optimizer: sgd
dataset: gtsrb
dataset_path: ../data/GTSRB
epochs: 200
frequency_save: 100
img_size: [32, 32, 3]
lr: 0.001
lr_scheduler: StepLR
steplr_stepsize: 100000
steplr_gamma: 0.1
model: resnet34
num_classes: 43
pratio: 0.4 # notice that this is inside the target class !
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005 # different from the yaml file, but the example code actually does not use wd in yaml file !?? The real wd in code actually is this value....
img_r_seq_folder_path: ../resource/refool_reflections
max_image_size: 560
ghost_rate: 0.49
alpha_t: -1.
offset:
- 0
- 0
sigma: -1.
ghost_alpha: -1.
