layer_name_list:
  - conv1
reverse_engineer_epochs: 1000
reverse_engineer_lr: 0.0001
reverse_engineer_weight_list: #[-0.01,0.0000001,0.00001,100]
  - -0.01
  - 0.0000001
  - 0.00001
  - 100
noise_training_threshold: 0.7
select_ratio: 0.1
attack_train_replace_imgs_path: ../resource/sunrise/cifar10_sunrise_x_train.npy #need to generate
attack_test_replace_imgs_path: ../resource/sunrise/cifar10_sunrise_x_test.npy #need to generate
attack_label_trans: all2one
attack_target: 0
batch_size: 32
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data/cifar10
epochs: 30
frequency_save: 100
img_size: [32, 32, 3]
lr: 0.01
lr_scheduler: StepLR
steplr_stepsize: 100000
steplr_gamma: 0.1
model: preactresnet18
num_classes: 10
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005