amp: False
device: cuda:0
attack_label_trans: all2one
attack_target: 0
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data
frequency_save: 100
batch_size: 128
lr: 0.01
lr_scheduler: MultiStepLR
steplr_milestones:
  - 20
  - 80
steplr_gamma: 0.1
model: preactresnet18
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: SSBA_replace
epochs: 100
pretrained_model_path: /workspace/chenhongrui/BackdoorBench/record/normal_cifar10_preactresnet18/attack_epoch_99.pt
layer_name_list:
  - conv1
#  - layer1
#  - layer2
#  - layer3
#  - layer4
reverse_engineer_lr: 0.001
detoxicant_ratio_require: 0.7
#poison_model_save_path_for_test: /workspace/chenhongrui/BackdoorBench/record/20220528_152412_dfst_attack_attack_SSBA_replace_9jF6/retrain_with_poison_epoch_99.pt