data: ag
batch_size: 32
optimizer: adam
epoch: 10
weight_decay: 0
lr: 2e-5
warmup_epochs: 3
clean_data_path: ../../data/clean/ag
poison_data_path: ../../data/poison/ag
save_path: ../../models/poison_bert_ag.pkl