bd_attack_SSBA_replace_cifar10:
  attack: SSBA_replace
  attack_test_replace_imgs_path: ../data/cifar10_SSBA/test.npy
  attack_train_replace_imgs_path: ../data/cifar10_SSBA/train.npy
  dataset: cifar10
  dataset_path: ../data/cifar10
bd_attack_blended:
  attack: blended
  attack_test_blended_alpha: 0.1
  attack_train_blended_alpha: 0.1
  attack_trigger_img_path: ../data/hello_kitty.jpeg
bd_attack_fix_patch_32_32:
  attack: fix_patch
  attack_trigger_loc:
  - - 26
    - 26
  - - 26
    - 27
  - - 27
    - 26
  - - 27
    - 27
  trigger_ptn:
  - 0
  - 0
  - 0
  - 0
bd_attack_fix_patch_64_64:
  attack: fix_patch
  attack_trigger_loc:
  - - 52
    - 52
  - - 52
    - 53
  - - 52
    - 54
  - - 52
    - 55
  - - 53
    - 52
  - - 53
    - 53
  - - 53
    - 54
  - - 53
    - 55
  - - 54
    - 52
  - - 54
    - 53
  - - 54
    - 54
  - - 54
    - 55
  - - 55
    - 52
  - - 55
    - 53
  - - 55
    - 54
  - - 55
    - 55
  trigger_ptn:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
bd_attack_input_cifar10:
  attack: input
  attack_test_pixel_perturb_limit: 5
  attack_train_pixel_perturb_limit: 5
  attack_trigger_img_path: ../data/hello_kitty.jpeg
data_celeba:
  dataset: celeba
  dataset_path: ../data/CelebA_attr
  img_size:
  - 64
  - 64
  - 3
  num_classes: 8
data_cifar10:
  dataset: cifar10
  dataset_path: ../data/cifar10
  img_size:
  - 32
  - 32
  - 3
  num_classes: 10
data_gtsrb:
  dataset: GTSRB
  dataset_path: ../data/GTSRB
  img_size:
  - 32
  - 32
  - 3
  num_classes: 43
data_tiny:
  dataset: tiny
  dataset_path: ../data/tiny-imagenet-200
  img_size:
  - 64
  - 64
  - 3
  num_classes: 200
train_normal:
  batch_size: 128
  client_optimizer: sgd
  epochs: 100
  lr: 0.01
  lr_scheduler: CosineAnnealingLR
  sgd_momentum: 0.9
  wd: 0.0005
