device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01

poison_rate: 0.1
target_type: 'all2one'
target_label: 0
trigger_type: 'squareTrigger'

model: 'preactresnet18'

method : 'all'
N_REPEAT: 5
N_EPOCH: 10
TRAIN_NUM: 2048
VAL_NUM: 256
TEST_NUM: 256
load_exist: False
