device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 200
batch_size: 128
num_workers: 4
lr: 0.01
lr_scheduler: ReduceLROnPlateau

poison_rate: 0.1
target_type: 'all2one'
target_label: 0
trigger_type: 'squareTrigger'

model: 'preactresnet18'
seed: 0
index: 

te_epochs: 10
print_freq: 50
momentum: 0.9
weight_decay: 1.0e-4
ratio: 0.05
beta1: 500
beta2: 1000
beta3: 1000
p: 2.0
threshold_clean: 70.0
threshold_bad: 90.0




