device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01

poison_rate: 0.1
target_type: 'all2one'
target_label: 0
trigger_type: 'squareTrigger'

model: 'resnet18'

n_sample: 100
n_test: 100
detection_boundary: 0.2
test_rounds: 10
s: 0.5
k: 4
grid-rescale: 1

