model: preactresnet18
data_root: ../data/cifar10
checkpoints: ./wanet/checkpoints
temps: ./temps 
device: cuda 
dataset: cifar10 
attack_mode: all2one 
bs: 128
lr_C: 0.01
schedulerC_milestones:
  - 100
  - 200
  - 300
  - 400
schedulerC_lambda: 0.1
n_iters: 1000
num_workers: 6
target_label: 0
pratio: 0.1
cross_ratio: 2  # rho_a = pratio, rho_n = pratio * cross_ratio
random_rotation: 10
random_crop: 5
s: 0.5
k: 4
grid_rescale: 1
random_seed: 0