attack_label_trans: all2one
attack_target: 0
batch_size: 128
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data/cifar10
epochs: 1000
frequency_save: 100
img_size: [32, 32, 3]
lr: 0.01
lr_scheduler: MultiStepLR
steplr_milestones:
  - 100
  - 200
  - 300
  - 400
steplr_gamma: 0.1
model: resnet18
num_classes: 10
pratio: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
warp_kernel_size: 4
warping_strength: 0.5
grid_rescale: 1
cross_ratio: 2
random_crop: 5
random_rotation: 10